# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(555, 329)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 531, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.layout_form = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.layout_form.setContentsMargins(0, 0, 0, 0)
        self.layout_form.setObjectName("layout_form")
        self.select_ground_beans = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_ground_beans.sizePolicy().hasHeightForWidth())
        self.select_ground_beans.setSizePolicy(sizePolicy)
        self.select_ground_beans.setObjectName("select_ground_beans")
        self.select_ground_beans.addItem("")
        self.select_ground_beans.addItem("")
        self.layout_form.addWidget(self.select_ground_beans, 5, 0, 1, 2)
        self.label_roasting_degree = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_roasting_degree.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_roasting_degree.setObjectName("label_roasting_degree")
        self.layout_form.addWidget(self.label_roasting_degree, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.layout_form.addItem(spacerItem, 4, 0, 1, 2)
        self.edit_title = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.edit_title.setObjectName("edit_title")
        self.layout_form.addWidget(self.edit_title, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.layout_form.addItem(spacerItem1, 6, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layout_form.addWidget(self.buttonBox, 14, 0, 1, 2)
        self.spin_price = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spin_price.setMaximum(9999999)
        self.spin_price.setObjectName("spin_price")
        self.layout_form.addWidget(self.spin_price, 10, 1, 1, 1)
        self.label_taste = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_taste.setObjectName("label_taste")
        self.layout_form.addWidget(self.label_taste, 7, 0, 1, 1)
        self.label_price = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_price.setObjectName("label_price")
        self.layout_form.addWidget(self.label_price, 10, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_title.setObjectName("label_title")
        self.layout_form.addWidget(self.label_title, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.layout_form.addItem(spacerItem2, 11, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.layout_form.addItem(spacerItem3, 9, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.layout_form.addItem(spacerItem4, 1, 0, 1, 2)
        self.edit_roasting_degree = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.edit_roasting_degree.setObjectName("edit_roasting_degree")
        self.layout_form.addWidget(self.edit_roasting_degree, 2, 1, 1, 1)
        self.edit_taste = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.edit_taste.setObjectName("edit_taste")
        self.layout_form.addWidget(self.edit_taste, 7, 1, 1, 1)
        self.label_info = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_info.setStyleSheet("QLabel {\n"
"color: rgb(255, 53, 53);\n"
"}")
        self.label_info.setText("")
        self.label_info.setObjectName("label_info")
        self.layout_form.addWidget(self.label_info, 13, 0, 1, 2)
        self.label_size = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_size.setObjectName("label_size")
        self.layout_form.addWidget(self.label_size, 12, 0, 1, 1)
        self.spin_size = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spin_size.setMaximum(9999999)
        self.spin_size.setObjectName("spin_size")
        self.layout_form.addWidget(self.spin_size, 12, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.select_ground_beans.setItemText(0, _translate("Dialog", "В зернах"))
        self.select_ground_beans.setItemText(1, _translate("Dialog", "Молотый"))
        self.label_roasting_degree.setText(_translate("Dialog", "Степень обжарки"))
        self.label_taste.setText(_translate("Dialog", "Описание вкуса"))
        self.label_price.setText(_translate("Dialog", "Цена"))
        self.label_title.setText(_translate("Dialog", "Название"))
        self.label_size.setText(_translate("Dialog", "Объем упаковки"))
